module loadAllForTesting where

open import addTick
open import addTickOperator
open import auxData
open import choiceAuxFunction
open import choiceSetU
open import dataAuxFunction
open import div
open import externalChoice
open import hidingOperator
open import interleave
open import internalChoice
open import interrupt
open import label
open import labelEq
open import lemFmap
open import parallelSimple
open import primitiveProcess
open import process
open import proofAssExt
open import proofAssInterleaving
open import proofInterruptLaw
open import ProofLawsSeq
open import proofMonadicLaw
open import proofRefLaw
open import proofRenamingSkip
open import proofSymExt
open import proofSymInterleaving
open import proofSymPar
open import proofTerHide
open import proofTerInter
open import proofTerPar
open import RefWithoutSize
open import renamingOperator
open import renamingResult
open import restrict
open import sequentialComposition
open import sequentialCompositionRev
open import showFunction
open import showLabelP
open import traceEquivalence
open import TraceWithoutSize
