module loadAllForTesting where

open import addTick
open import addTickOperator
open import auxData
open import choiceAuxFunction
open import choiceSetU
open import codeAsInTyDe2016Paper
open import dataAuxFunction
open import div
open import efq
open import eliminationExample
open import exampleFinFun
open import externalChoice
open import finn
open import hidingOperator
open import interleave
open import internalChoice
open import interrupt
open import IOExtchoice
open import IOInterleav
open import IOInternalchoice
open import IOSeqCom
open import label
open import labelEq
open import parallel
open import parallelSimple
open import preFix
open import primitiveProcess
open import process
open import rec
open import renamingOperator
open import renamingProcess
open import renamingResult
open import renamingResultOriginal
open import restrict
open import sequentialComposition
open import setLabel
open import showFunction
open import showLabelP
open import simulator
open import simulatorCutDown
open import skip
open import test
open import testExampleProcesses
open import testInternalChoice
open import testRec
open import testRenamingOperator
open import testRenamingResult
open import testShowFunction
open import testShowLabelP
open import Unit
